# Tool Options
tool_tier: vanilla_hammers:fiery
tool_category: minecraft:pickaxe
break_speed: 2
attack_damage: 6
attack_speed: 1.7

# Hammer Options
range: 1
depth: 1
hardness_tolerance: 0

# Damageable Options
durability: 1560
item_damage_on_attack_entity: 2
item_damage_on_break_block: 1
repair_ingredient: "minecraft:magma_block"

# Enchantable Options
enchantment_value: 15
enchantment_categories: ["vanilla_hammers:hammer", "minecraft:digger", "minecraft:breakable"]