# Tool Options
tool_tier: minecraft:iron
tool_category: minecraft:pickaxe
break_speed: 1.7
attack_damage: 5
attack_speed: 1.2

# Hammer Options
range: 1
depth: 1
hardness_tolerance: 0
slowdown_per_block: 0.2

# Damageable Options
durability: 250
item_damage_on_attack_entity: 2
item_damage_on_break_block: 1
repair_ingredient: "minecraft:iron_ingot"

# Enchantable Options
enchantment_value: 14
supported_enchantments:
  - "vanilla_hammers:curse_of_gigantism"
  - "minecraft:efficiency"
  - "minecraft:silk_touch"
  - "minecraft:fortune"
  - "minecraft:unbreaking"
  - "minecraft:mending"