# Tool Options
tool_tier: vanilla_hammers:obsidian
tool_category: minecraft:pickaxe
break_speed: 1.4
attack_damage: 7
attack_speed: 0.5

# Hammer Options
range: 1
depth: 1
hardness_tolerance: 0
slowdown_per_block: 0.2

# Damageable Options
durability: 2500
item_damage_on_attack_entity: 2
item_damage_on_break_block: 1
repair_ingredient: "minecraft:obsidian"

# Enchantable Options
enchantment_value: 5
supported_enchantments:
  - "vanilla_hammers:curse_of_gigantism"
  - "minecraft:efficiency"
  - "minecraft:silk_touch"
  - "minecraft:fortune"
  - "minecraft:unbreaking"
  - "minecraft:mending"